Add ggez example (#161)
* Rendering example for ggez

* Update ggez example

* Refactoring for ggez example

* Re-add example entry I accidently removed

* Add note about caching layer_batches in ggez ex

* Update contributors list

* Change format string in ggez example to work on older rust versions

* Add libasound2-dev and libudev-dev to rust workflow apt install

* ggez: use CARGO_MANIFEST_DIR

Co-authored-by: Alejandro Perea <alexpro820@gmail.com>

* ggez: destructure some variables

Co-authored-by: Thorbjørn Lindeijer <bjorn@lindeijer.nl>

* ggez: more destructuring

* ggez: make left mouse also drag

* ggez: reduce time_since_start calls, make get_tile_rect return Rect

* Use the Loader

* Refactor some minor things

* Don't center the map by default

* Add batch caching to ggez example

Cache gets invalidated when panning/zooming or every frame while animating
The performance improvement would be more noticeable if there were more layers & more tilesets per layer

* Cargo fmt

* Polish

* Fixed 'bounds' function and removed unused import

* Apparently clippy check now needs alsa

thread 'main' panicked at '`"pkg-config" "--libs" "--cflags" "alsa"` did not exit successfully: exit status: 1
error: could not find system library 'alsa' required by the 'alsa-sys' crate

* Also install udev dependency

"Package libudev was not found in the pkg-config search path."

Co-authored-by: Alejandro Perea <alexpro820@gmail.com>
Co-authored-by: Thorbjørn Lindeijer <bjorn@lindeijer.nl>
Co-authored-by: aleokdev <aleok.inf@gmail.com>